security:
    password_hashers:
        App\Domain\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Domain\Entity\User
                property: email

    firewalls:
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: App\Security\Handler\LoginSuccessHandler
                failure_handler: App\Security\Handler\LoginFailureHandler

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/registration, roles: PUBLIC_ACCESS }
        - { path: ^/api/user/create, roles: ROLE_ADMIN }
        - { path: ^/api, roles: ROLE_USER }